### ISSUE TITLE
Help in finding a library for a PS2 controller under RP2040

### ISSUE THREAD

**Issue by Crazy-Child** [Loc15/PicoGamepadConverter#1]
Hi, friend.
I'm just starting to understand the RP2040, I'm looking for how to connect a controller from PS2.
I couldn't find anything on the Internet. I just came across your development. As I understand it, this is something universal and beyond what I need.
Could you help or advise where I can find a library for using a PS2 controller for homemade projects on the RP2040?

**Comment by Loc15** [comment]
Hi mate, if you need a library you could use this [circuit-python library](https://github.com/todbot/CircuitPython_PS2Controller) . If you need C code, my code is a library itself you need folder src/host_files/psx-lib and adding to main on similar way how I do it.
