### ISSUE TITLE
Change default for Host

### ISSUE THREAD

**Issue by andrewfstratton** [Loc15/PicoGamepadConverter#3]
Please could the Host default be changed to DirectInput - (arguably) the most likely setup needed - XInput to XInput seems to be extremely unlikely.

**Comment by Loc15** [comment]
Similar to the other issue. Last configuration will be shown.

**Comment by Loc15** [comment]
Similar to the other issue.

**Comment by andrewfstratton** [comment]
Actually I meant the default after flashing with a UF2 - which appears to be Xinput to Xinput because the default config isn't shown...
