### ISSUE TITLE
Improving wording/layout for web page

### ISSUE THREAD

**Issue by andrewfstratton** [Loc15/PicoGamepadConverter#4]
I found the web page confusing when first using it.  Could this following help (new) users:

1. Put an explanation that Host is the plugged in real gamepad and Device is how the Pico looks to a Computer
  - possibly give an/some example/s
  - putting the Device setting in (further) features would simplify the typical usage - or just putting it further down the page...
2. Include a link to the github for further detail
3. More detail on 'Block Analogues' I have no idea what these are.

**Comment by Loc15** [comment]
> 3. More detail on 'Block Analogues' I have no idea what these are

Block Analogues means to ignore input from gamepad analog stick, it gonna keep in the center.

**Comment by andrewfstratton** [comment]
Would 'Ignore Analogue (axis)' be better understood?  I thought Block meant that the analogues work in a 'block' mode, e.g  like analogue to digital...

**Comment by Loc15** [comment]
Disable analog stick would be better, I going to adding to documentation on the next update.
